name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '42 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache next prompts
        uses: actions/cache@v4
        with:
          path: src/next-prompts.txt
          # Caches are immutable so the key needs to be unique
          key: next-prompts-${{ github.run_number }}
          # With this key, Github will retrieve the nearest (most recent) key
          restore-keys: |
            next-prompts

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          cname: journaling.rbarbazz.com
          publish_dir: ./dist

      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          committer_username: 'github-actions[bot]'
          committer_email: '41898282+github-actions[bot]@users.noreply.github.com'
